#API
@password={{$dotenv PASSWORD}}
@username={{$dotenv USERNAME}}
@email={{$dotenv GMAIL}}
@userId=6  #
### Getting all users
GET http://localhost:8080/api/users

### Create a user
POST http://localhost:8080/api/auth/local/register
Content-Type: application/json

{
    
  "email": "{{email}}",
  "username": "{{username}}",
  "password": "{{password}}"
   
}

### Update a user by ID
PUT http://localhost:8080/api/users/{{userId}}
Content-Type: application/json

{
  "username": "ftasdasdnapsdfsattttt_updated",
  "email": "sorayut-no@rmutp.ac.th"
}

### Delete user by ID
DELETE http://localhost:8080/api/users/{{userId}}
