# API
@password=$($env password)
### Getting all user
GET http://localhost:8080/api/users

### Create a user
POST http://localhost:8080/api/auth/local/register
Content-Type: application/json

{
    "username": "Sorayut Nookaew",
    "email": "sorayut-no@rmutp.ac.th",
    "password": "{{password}}"
}